
author: Abdul Jeter # author name
email: abdulazizjtr@gmail.com # author email
keywords: "abdul jeter, abdul, jeter, Abdul, Jeter, Abdul Jeter, Abdul Aziz Jeter, abdul aziz jeter, ABDUL JETER, ABDUL AZIZ JETER, abdulj github, abdul-j, abdul has a website, abdul has a blog, abdulisabroad, abdul aomori, abdul philly, abdul 2024" # html meta keywords
baseurl: "" # the subpath of your site, e.g. /blog
permalink: pretty
name: Abdul Jeter
title: "Abdul's Blog"
description: "Welcome to my blog!"
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title:output_ext
twitter:
  username: prodfuze
social:
  name: Abdul Jeter
  links:
    - https://www.twitter.com/prodfuze
    - https://www.instagram.com/abdul.7z
    - https://www.github.com/abdul-j
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-include-cache
webmaster_verifications:
  google: googlefae959dd83b9ac7e
gems:
  - jekyll-compass
  - jekyll-seo-tag
header_pages:
  - about.html
  - blog.html
feed:
  path: feed.xml # Default path
  title: "Abdul's Blog"
  description: "Updates and articles from my Blog"
  author_name: "Abdul Jeter"
  author_email: "abduljtr@gmail.com"
  copyright: "2024 Abdul's Blog"