
author: Abdul Aziz Jeter # author name
email: abdulazizjtr@gmail.com # author email
keywords: "abdul jeter, abdul, jeter, Abdul, Jeter, Abdul Jeter, Abdul Aziz Jeter, abdul aziz jeter, ABDUL JETER, ABDUL AZIZ JETER, abdulj github, abdul-j, abdul has a website, abdul has a blog, abdulisabroad, abdul aomori, abdul philly, abdul 2024" # html meta keywords
baseurl: "/" # the subpath of your site, e.g. /blog
name: Abdul Jeter
markdown: kramdown
permalink: /:categories/:title/
twitter:
  username: prodfuze
social:
  name: Abdul Jeter
  links:
    - https://www.twitter.com/prodfuze
    - https://www.instagram.com/abdul.7z
    - https://www.github.com/abdul-j
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
webmaster_verifications:
  google: googlefae959dd83b9ac7e
gems:
  - jekyll-compass
  - jekyll-seo-tag